### ISSUE TITLE
What does '>=' mean on "YDist(0,27,>=)" ?

### ISSUE THREAD

**Issue by felipesanches** [felipesanches/Hinting_Decompiler#1]
@laerm0, on glyph program for 'j' on Roboto-VF.ttf I noticed that the VTT Talk code contains a line like this:

```
YDist(0,27,>=)
```

I wonder what '>=' means in there. I previously thought only a point index would be valid as an argument to YDist.

**Comment by felipesanches** [comment]
![screenshot at 2018-08-13 10 03 01](https://user-images.githubusercontent.com/213676/44033419-d9d6bf80-9ef9-11e8-8407-4fdcf973b1ad.png)

**Comment by felipesanches** [comment]
Actually... I think I got it. It seems that '>=' is the high-level way of expressing the flag 'b' as described in the spec here:
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM05/Chap5.html#MDRP

**Comment by laerm0** [comment]
Ah, yes, that's it @felipesanches.
